version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      --api.insecure=true 
      --providers.docker 
      --log.level=DEBUG 

  auth-server:
    build: ./auth
    container_name: auth-server
    ports:
      - "8000:8000"
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.auth.rule=Host(`localhost`)"
       - "traefik.http.services.auth.loadbalancer.server.port=8000"
    depends_on:
      - mongo

  event-server:
    build: ./events
    container_name: events-server
    ports:
      - "8888:8888"
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=event_table
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.event-server.rule=Host(`localhost`)"
      - "traefik.http.services.event-server.loadbalancer.server.port=8888"
    depends_on:
      - postgres
      - kafka


  postgres:
    image: postgres:latest
    hostname: postgres.local
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_table
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.0
    container_name: auth-service-mongo
    hostname: mongo.local
    restart: always
    ports:
      - "27017:27017"
    command:
      - "mongod"
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: apache/kafka-native
    ports:
      - "9093:9093"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka

volumes:
  mongo-data:
  postgres-data: