networks:
  shared-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      --api.insecure=true 
      --providers.docker 
      --log.level=DEBUG 

# To run:
# docker-compose -f docker-compose.yml -f auth/auth-stack.yml -f events/events-stack.yml  -f orders/orders-stack.yml up
