version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/auth/traefik/traefik.yml
      - ./traefik/dynamic:/auth/traefik/dynamic
    command: --api.insecure=true --providers.docker --log.level=DEBUG

  auth-server:
    build: ./auth
    container_name: auth-server
    ports:
      - "8080:8080" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-server.rule=Host(`localhost`)"
      - "traefik.http.routers.auth-server.entrypoints=web"
      - "traefik.http.routers.auth-server.middlewares=auth-middleware"
      - "traefik.http.services.auth-server.loadbalancer.server.port=8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    hostname: mongo.local
    restart: always
    ports:
      - "27017:27017"
    command:
      - "mongod"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: