version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8081:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
    command: --api.insecure=true --providers.docker

  auth-server:
    build: ./auth
    container_name: auth-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-server.rule=Host(`auth.example.com`)"
      - "traefik.http.routers.auth-server.entrypoints=web"
      - "traefik.http.routers.auth-server.middlewares=auth-middleware"
    depends_on:
      - mongoDB

  mongoDB:
    image: mongo:4.0
    hostname: mongo.local
    restart: always
    ports:
      - "27017:27017"
    labels:
      - "traefik.tcp.routers.mongo.rule=HostSNI(`mongo.local`)"
      - "traefik.tcp.routers.mongo.tls.passthrough=true"
      - "traefik.tcp.routers.mongo.entrypoints=mongo"
      - "traefik.enable=true"
      - "traefik.http.routers.auth-server.rule=Host(`auth.com`)"
      - "traefik.http.routers.auth-server.entrypoints=web"
      - "traefik.http.routers.auth-server.middlewares=auth-middleware"
    command:
      - "mongod"
      - "--sslMode=requireSSL"
      - "--sslPEMKeyFile=/certs/mongo.pem"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: