services:
  event-server:
    build: ./events
    container_name: events-server
    ports:
      - "8888:8888"
    environment:
      - PGHOST=postgres_primary
      - PGPORT=5432
      - PGUSER=postgres_primary
      - PGPASSWORD=postgres
      - PGDATABASE=event_table
      - PGHOST_2=postgres_outbox
      - PGPORT_2=5432
      - PGUSER_2=postgres_outbox
      - PGPASSWORD_2=postgres
      - PGDATABASE_2=outbox
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.event-server.rule=Host(`event.localhost`)"
      - "traefik.http.routers.app.middlewares=auth-forward"
      - "traefik.http.middlewares.auth-forward.forwardauth.address=http://auth-server:8000/auth"
      - "traefik.http.middlewares.auth-forward.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.auth-forward.forwardauth.authResponseHeaders=X-User-Id,X-User-Role"
    depends_on:
      - postgres-primary
      - postgres-outbox
      - kafka
    networks:
      - shared-network

  postgres-primary:
    image: postgres:latest
    container_name: events-db
    hostname: postgres_primary
    restart: always
    environment:
      - POSTGRES_USER=postgres_primary
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event_table
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data
    networks:
      - shared-network

  postgres-outbox:
    image: postgres:latest
    container_name: outbox-db
    hostname: postgres_outbox
    restart: always
    environment:
      - POSTGRES_USER=postgres_outbox
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=outbox
    volumes:
      - postgres-outbox-data:/var/lib/postgresql/data
    networks:
      - shared-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - shared-network

  kafka:
    image: apache/kafka-native
    container_name: events-kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shared-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest  # Fixed image name
    container_name: events-kafka-ui
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

volumes:
  postgres-primary-data:
  postgres-outbox-data: